// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database_query

import (
	"time"
)

type User struct {
	ID           int32
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
