// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: user.sql

package database_query

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT name FROM user WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
