version: "3.8"

services:
  app:
    image: app
    env_file:
      - ./.env
    container_name: app
    build: .
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - network

  db:
    image: mysql:8.0.29
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    networks:
      - network
  
  vue:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    container_name: vue_container
    tty: true
    volumes:
      - ./vue-app/vue-app:/app/vue
    command: sh -c "cd /app/vue && npm i && npm run dev"
    ports:
      - 3000:3000

networks:
  network: