version: "3.8"

services:
  app:
    image: app
    container_name: app
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app/go:/app
    depends_on:
      - db
    networks:
      - network
    command: ["air", "-c", "/app/.air.toml"]

  db:
    image: mysql:8.0.29
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    networks:
      - network

  vue:
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile
    container_name: vue_container
    tty: true
    volumes:
      - ./app/vue:/vue
    command: sh -c "cd /vue && pnpm i && pnpm run dev"
    ports:
      - 3000:3000

networks:
  network:
