linters:
  enable:
    - decorder
    - dupl
    - dupword
    - exportloopref
    - funlen
    - gofmt
    - goimports
    - gomnd
    - gosimple
    - nilerr
    - tparallel
    - unused
    - whitespace