name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'app/vue/src/**'
      - 'app/vue/tests/**'
      - 'app/vue/pnpm-lock.yaml'
      - '.github/workflows/main.yml'
  pull_request:
    paths:
      - 'app/vue/src/**'
      - 'app/vue/tests/**'
      - 'app/vue/pnpm-lock.yaml'
      - '.github/workflows/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('app/vue/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install
        working-directory: app/vue

      - name: Type Check
        run: pnpm type-check
        working-directory: app/vue

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: app/vue

      - name: Run e2e tests
        run: |
          pnpm build
          pnpm test:ci-e2e
        working-directory: app/vue

      - name: Run unit tests
        run: pnpm test:ci
        working-directory: app/vue

      - name: Coverage
        uses: davelosert/vitest-coverage-report-action@v2.3.1
        with:
          working-directory: app/vue
        if: ${{ always() }}
